services:
  turtlebot3:
    container_name: turtlebot3
    image: robotis/turtlebot3:jazzy-latest
    build:
      context: ../..
      dockerfile: docker/jazzy/Dockerfile
    tty: true
    restart: always
    init: true
    stop_signal: SIGINT
    stop_grace_period: 20s
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    ipc: host
    pid: host
    environment:
     - TURTLEBOT3_MODEL=waffle_pi
     - LDS_MODEL=LDS-02
     - ROS_DOMAIN_ID=30
     - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
     - CYCLONEDDS_URI=file:///root/turtlebot3_ws/src/turtlebot3/docker/jazzy/cyclonedds.xml
     - DDS_IFACE=${DDS_IFACE:-wlan0}
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /run/udev:/run/udev
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ../../:/root/turtlebot3_ws/src/turtlebot3
    privileged: true
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /root/turtlebot3_ws/install/setup.bash &&
               exec ros2 launch turtlebot3_bringup bringup.launch.py"
