twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      teleop:
        topic:    cmd_vel_teleop
        timeout:  0.2
        priority: 100
      nav2:
        topic:    cmd_vel_nav2
        timeout:  0.2
        priority: 50
      watchdog:
        topic:    cmd_vel_watchdog
        timeout:  0.5
        priority: 1
